;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-delete
        evil-delete-char
        evil-force-normal-state
        evil-forward-char
        evil-forward-word-begin
        evil-insert
        evil-next-line
        evil-normal-state
        evil-yank
        ))

(setq mc/cmds-to-run-once
      '(
        evil-backward-char
        evil-mouse-drag-region
        mark-whole-buffer
        mouse-set-region
        smex
        ))
